### ISSUE TITLE
Rename to kubectx

### ISSUE THREAD

**Issue by danmasta** [thomasliddledba/kubectxwin#2]
I don't see any reason to change the name to [kubectxwin](https://github.com/ahmetb/kubectx/issues/29). No other tooling does this. It would be helpful to have the same binary name in windows as we have on mac/linux. I changed the exe name myself, but other people would probably appreciate the change as well. Both implementations serve the same purpose.

As noted [here](https://github.com/ahmetb/kubectx/issues/29) the other author doesn't intend on adding windows support.

Please note other tools like nvm that use the same name across different implementations:
https://github.com/creationix/nvm
https://github.com/coreybutler/nvm-windows

**Comment by thomasliddledba** [comment]
The author asked that I change the name to something other then kubectx.  We agreed on kubectxwin.  I'm only honoring my agreement.

**Comment by danmasta** [comment]
No worries, that's understandable. Thanks anyway for sharing the package!
